### ISSUE TITLE
QT Client 需要的服务端接口实现

### ISSUE THREAD

**Issue by Sh1n3zZ** [aiaresearch/homeworkGun#12]
- [x] 1.获取某班学生 GET
- [x] 2.未到截止日期的作业 GET
- [x] 3.需要提交的作业项 GET
- [x] 4.用户登录状态（Success / Fail） GET
- [x] #13
- [x] 6.用户登录 / 注册 POST

将 Python 实现重构为 Golang 实现

**Comment by Sh1n3zZ** [comment]
[登录实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/login.go)
方法 POST
接口 /login
请求参数
Body 参数如下 格式 json：
```json
{
  "account": "user@example.com",
  "passwd": "securePassword123"
}
```
成功返回（此处为脱敏后的token数据，实际返回 token 数据参考实现代码）
```json
{
    "token": "eyJhb************BeI8ip1-JzUEOs"
}
```

[注册实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/register.go)
方法 POST
接口 /register
请求参数
Body 参数如下 格式 json：
```json
{
  "account": "user@example.com",
  "passwd": "securePassword123"
}
```
成功返回
```json
{
    "message": "Registration successful"
}
```

[校验实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/profile.go)
方法 GET
接口 /user
请求参数
Header 参数如下（eyJhb************BeI8ip1-JzUEOs 为登陆后返回的 token 数据，此处做脱敏处理）：
```
Authorization string eyJhb************BeI8ip1-JzUEOs
```
or
```
export interface Request {
    Authorization: string;
    [property: string]: any;
}
```
成功返回
```json
{
    "message": "User profile accessed successfully"
}
```

**Comment by Sh1n3zZ** [comment]
```
POST /login HTTP/1.1
Host: localhost:1145
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json
Content-Length: 71

{
  "account": "user@example.com",
  "passwd": "securePassword123"
}
```
```
POST /register HTTP/1.1
Host: localhost:1145
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json
Content-Length: 72

{
  "account": "user2@example.com",
  "passwd": "securePassword123"
}
```
```
GET /user HTTP/1.1
Host: localhost:1145
Authorization: eyJhb************BeI8ip1-JzUEOs
User-Agent: Apifox/1.0.0 (https://apifox.com)
```

@3q1u

**Comment by Sh1n3zZ** [comment]
具体使用 Golang+Gin+JWT+PostgreSQL+localStorage 实现， `localStorage` 实际生产环境比现有 `Cookies` 更安全

**Comment by BurstWhite** [comment]
收到，感谢！

**Comment by BurstWhite** [comment]
@Sh1n3zZ 可否在login时返回该用户所能查看的班级？

**Comment by Sh1n3zZ** [comment]
> @Sh1n3zZ 可否在login时返回该用户所能查看的班级？

有两种实现方式：在你 POST 完 login 接口得到 successful 的 return 后直接 GET 查看班级的接口或我这里在 successful 后直接 return 一个 301 过去一个 GET 接口，你更偏向于哪一种实现方式，前端 or 后端

Regard,
Sh1n3zZ.

**Comment by microboym** [comment]
@Sh1n3zZ The so-called "QT client" is the the data collector agent installed to the machine in every classroom, which is in a different role than the frontend page (pure admin, for teacher). Should we separate the users of classes(qt) and those of teachers (pure admin)? And should we move all the endpoints for qt into a sub dir, eg. `/classroom_endpoint/{login, upload_submission, fetch_students_info}`?

**Comment by Sh1n3zZ** [comment]
@microboym ,
Now that the account system is in place, is it possible to consider using the account system for authentication?

Regards,
Sh1n3zZ

**Comment by 3q1u** [comment]
> > @Sh1n3zZ 可否在login时返回该用户所能查看的班级？
> 
> 有两种实现方式：在你 POST 完 login 接口得到 successful 的 return 后直接 GET 查看班级的接口或我这里在 successful 后直接 return 一个 301 过去一个 GET 接口，你更偏向于哪一种实现方式，前端 or 后端
> 
> Regard, Sh1n3zZ.

倾向于前端

**Comment by BurstWhite** [comment]
> > @Sh1n3zZ 可否在login时返回该用户所能查看的班级？
> 
> 有两种实现方式：在你 POST 完 login 接口得到 successful 的 return 后直接 GET 查看班级的接口或我这里在 successful 后直接 return 一个 301 过去一个 GET 接口，你更偏向于哪一种实现方式，前端 or 后端
> 
> Regard, Sh1n3zZ.

倾向于前端发get

**Comment by BurstWhite** [comment]
@Sh1n3zZ 另外，请提供查询学生列表的请求参数，谢谢

**Comment by Sh1n3zZ** [comment]
收到，晚上回去处理，该 issue 下有部分未完成 ToDoList 需等数据库架构重构完成后继续跟进

**Comment by BurstWhite** [comment]
收到

**Comment by BurstWhite** [comment]
@Sh1n3zZ /students的请求参数格式是什么，请给一个示例
我尝试了如下请求：`response = requests.get(url, {'class' : class})`,
但是返回404

**Comment by Sh1n3zZ** [comment]
暂未实现，今晚跟进，建议先完成登录注册和token校验部分的前后端

**Comment by BurstWhite** [comment]
收到

**Comment by Sh1n3zZ** [comment]
@3q1u ,

下午好，更新了两个接口，抱歉最近比较忙，文档拖到现在才给。

[创建作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/workcreate.go)
方法 POST
接口 /create
请求参数
```python
import http.client
import json

conn = http.client.HTTPSConnection("localhost", 1145)
payload = json.dumps({
   "homework_id": 1,
   "submission_required": "1#2#3#4#5#6#7",
   "start_date": "2024-03-01",
   "end_date": "2024-03-04"
})
headers = {
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
   'Content-Type': 'application/json'
}
conn.request("POST", "/create", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))
```
参数解释：
`homework_id` 为当前创建作业的 ID 号，非自增，自增有单独列，教师端用接口
`submission_required` 为需要提交的作业科目，用 1-7 分别表示七科，自行定义
`start_date` 为作业起始日
`end_data` 为提交截止日

[提交作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/worksub.go)
方法 POST
接口 /submit
请求参数
```python
import http.client
import json

conn = http.client.HTTPSConnection("localhost", 1145)
payload = json.dumps({
   "school_id": "37013171707",
   "subject_id": 456,
   "homework_id": 1
})
headers = {
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
   'Content-Type': 'application/json'
}
conn.request("POST", "/submit", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))
```
特别注意 `school_id` 类型

以上为本地调试，需联网调试自行修改 Host / Port

Regards,
Sh1n3zZ

**Comment by microboym** [comment]
hi there 

@Sh1n3zZ 我们在实际部署时可能会使用 docker，请问方便提供 dockerfile 吗

**Comment by BurstWhite** [comment]
> @3q1u ,
> 
> 下午好，更新了两个接口，抱歉最近比较忙，文档拖到现在才给。
> 
> [创建作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/workcreate.go) 方法 POST 接口 /create 请求参数
> 
> ```python
> import http.client
> import json
> 
> conn = http.client.HTTPSConnection("localhost", 1145)
> payload = json.dumps({
>    "homework_id": 1,
>    "submission_required": "1#2#3#4#5#6#7",
>    "start_date": "2024-03-01",
>    "end_date": "2024-03-04"
> })
> headers = {
>    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
>    'Content-Type': 'application/json'
> }
> conn.request("POST", "/create", payload, headers)
> res = conn.getresponse()
> data = res.read()
> print(data.decode("utf-8"))
> ```
> 
> 参数解释： `homework_id` 为当前创建作业的 ID 号，非自增，自增有单独列，教师端用接口 `submission_required` 为需要提交的作业科目，用 1-7 分别表示七科，自行定义 `start_date` 为作业起始日 `end_data` 为提交截止日
> 
> [提交作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/worksub.go) 方法 POST 接口 /submit 请求参数
> 
> ```python
> import http.client
> import json
> 
> conn = http.client.HTTPSConnection("localhost", 1145)
> payload = json.dumps({
>    "school_id": "37013171707",
>    "subject_id": 456,
>    "homework_id": 1
> })
> headers = {
>    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
>    'Content-Type': 'application/json'
> }
> conn.request("POST", "/submit", payload, headers)
> res = conn.getresponse()
> data = res.read()
> print(data.decode("utf-8"))
> ```
> 
> 特别注意 `school_id` 类型
> 
> 以上为本地调试，需联网调试自行修改 Host / Port
> 
> Regards, Sh1n3zZ

@Sh1n3zZ 晚上好，请问```homework_id```是本地自定义的标识吗
另外，请问```get_students```方法何时实现

**Comment by Sh1n3zZ** [comment]
> > @3q1u ,
> > 下午好，更新了两个接口，抱歉最近比较忙，文档拖到现在才给。
> > [创建作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/workcreate.go) 方法 POST 接口 /create 请求参数
> > ```python
> > import http.client
> > import json
> > 
> > conn = http.client.HTTPSConnection("localhost", 1145)
> > payload = json.dumps({
> >    "homework_id": 1,
> >    "submission_required": "1#2#3#4#5#6#7",
> >    "start_date": "2024-03-01",
> >    "end_date": "2024-03-04"
> > })
> > headers = {
> >    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
> >    'Content-Type': 'application/json'
> > }
> > conn.request("POST", "/create", payload, headers)
> > res = conn.getresponse()
> > data = res.read()
> > print(data.decode("utf-8"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参数解释： `homework_id` 为当前创建作业的 ID 号，非自增，自增有单独列，教师端用接口 `submission_required` 为需要提交的作业科目，用 1-7 分别表示七科，自行定义 `start_date` 为作业起始日 `end_data` 为提交截止日
> > [提交作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/worksub.go) 方法 POST 接口 /submit 请求参数
> > ```python
> > import http.client
> > import json
> > 
> > conn = http.client.HTTPSConnection("localhost", 1145)
> > payload = json.dumps({
> >    "school_id": "37013171707",
> >    "subject_id": 456,
> >    "homework_id": 1
> > })
> > headers = {
> >    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
> >    'Content-Type': 'application/json'
> > }
> > conn.request("POST", "/submit", payload, headers)
> > res = conn.getresponse()
> > data = res.read()
> > print(data.decode("utf-8"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 特别注意 `school_id` 类型
> > 以上为本地调试，需联网调试自行修改 Host / Port
> > Regards, Sh1n3zZ
> 
> @Sh1n3zZ 晚上好，请问`homework_id`是本地自定义的标识吗 另外，请问`get_students`方法何时实现

@3q1u ,

`homework_id` 为与 @skyfrostz 沟通后决定调整的架构，为统一学生标识 id （即全校学号）而非班级学号
`get_students` 现在开始做（其实已经做好了，但是因为改架构需要重新调整）

**Comment by BurstWhite** [comment]
收到

**Comment by BurstWhite** [comment]
@Sh1n3zZ ```homework_id```项是如何生成的？随机数字还是UUID

**Comment by Sh1n3zZ** [comment]
为教师布置作业时的自增值，用于校对单次作业需要提交的全部作业类型
@3q1u

**Comment by BurstWhite** [comment]
收到 qt client端有无布置作业的权限

**Comment by Sh1n3zZ** [comment]
建议仅给教师端该权限

**Comment by BurstWhite** [comment]
收到

**Comment by 3q1u** [comment]
@

> @3q1u ,
> 
> 下午好，更新了两个接口，抱歉最近比较忙，文档拖到现在才给。
> 
> [创建作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/workcreate.go) 方法 POST 接口 /create 请求参数
> 
> ```python
> import http.client
> import json
> 
> conn = http.client.HTTPSConnection("localhost", 1145)
> payload = json.dumps({
>    "homework_id": 1,
>    "submission_required": "1#2#3#4#5#6#7",
>    "start_date": "2024-03-01",
>    "end_date": "2024-03-04"
> })
> headers = {
>    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
>    'Content-Type': 'application/json'
> }
> conn.request("POST", "/create", payload, headers)
> res = conn.getresponse()
> data = res.read()
> print(data.decode("utf-8"))
> ```
> 
> 参数解释： `homework_id` 为当前创建作业的 ID 号，非自增，自增有单独列，教师端用接口 `submission_required` 为需要提交的作业科目，用 1-7 分别表示七科，自行定义 `start_date` 为作业起始日 `end_data` 为提交截止日
我们注意到，在实际应用场景下，布置作业往往是由课代表完成的，因此我建议向学生端开放布置作业权限

**Comment by BurstWhite** [comment]
我与 @skyfrostz 注意到，在具体应用场景下，布置作业往往是由课代表完成的，因此我建议对学生端开放布置作业的权限 @Sh1n3zZ

**Comment by Sh1n3zZ** [comment]
> > @3q1u ,
> > 下午好，更新了两个接口，抱歉最近比较忙，文档拖到现在才给。
> > [创建作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/workcreate.go) 方法 POST 接口 /create 请求参数
> > ```python
> > import http.client
> > import json
> > 
> > conn = http.client.HTTPSConnection("localhost", 1145)
> > payload = json.dumps({
> >    "homework_id": 1,
> >    "submission_required": "1#2#3#4#5#6#7",
> >    "start_date": "2024-03-01",
> >    "end_date": "2024-03-04"
> > })
> > headers = {
> >    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
> >    'Content-Type': 'application/json'
> > }
> > conn.request("POST", "/create", payload, headers)
> > res = conn.getresponse()
> > data = res.read()
> > print(data.decode("utf-8"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参数解释： `homework_id` 为当前创建作业的 ID 号，非自增，自增有单独列，教师端用接口 `submission_required` 为需要提交的作业科目，用 1-7 分别表示七科，自行定义 `start_date` 为作业起始日 `end_data` 为提交截止日
> > [提交作业实现](https://github.com/aiaresearch/homeworkGun/blob/dev/go_api/handlers/worksub.go) 方法 POST 接口 /submit 请求参数
> > ```python
> > import http.client
> > import json
> > 
> > conn = http.client.HTTPSConnection("localhost", 1145)
> > payload = json.dumps({
> >    "school_id": "37013171707",
> >    "subject_id": 456,
> >    "homework_id": 1
> > })
> > headers = {
> >    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
> >    'Content-Type': 'application/json'
> > }
> > conn.request("POST", "/submit", payload, headers)
> > res = conn.getresponse()
> > data = res.read()
> > print(data.decode("utf-8"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 特别注意 `school_id` 类型
> > 以上为本地调试，需联网调试自行修改 Host / Port
> > Regards, Sh1n3zZ
> 
> @Sh1n3zZ 晚上好，请问`homework_id`是本地自定义的标识吗 另外，请问`get_students`方法何时实现

已实现

请求示例
```Python
import http.client

conn = http.client.HTTPSConnection("localhost", 1145)
payload = ''
headers = {
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)'
}
conn.request("GET", "/students?class=12", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))
```

返回示例
```json
{
    "names": [
        "Ueno Ayato",
        "Wu Ka Keung",
        "Ethel Campbell",
        "Tony Aguilar",
        "George Fox",
        "Mui Sze Yu",
        "Cui Ziyi",
        "Fan Jiehong",
        "Yan Shihan",
        "Nakamura Hina",
        "Han Anqi",
        "Kono Ayano",
        "Lois Cook",
        "Meng Ziyi",
        "Mui Ka Man",
        "Shi Yunxi",
        "Morita Aoi",
        "Nakagawa Ayato",
        "Chow Chieh Lun",
        "Kaneko Ayano",
        "Jiang Zhiyuan",
        "Jin Ziyi",
        "Siu Yun Fat",
        "Yamaguchi Ayato",
        "Watanabe Tsubasa",
        "Meng Sze Kwan",
        "Andrew Martin",
        "Duan Zhennan",
        "Ota Rin",
        "Sheh Wai San",
        "Che Chiu Wai",
        "Kudo Hikaru",
        "Yue Wai Yee",
        "Shen Zitao",
        "Ichikawa Momoe",
        "Maruyama Minato",
        "Sit Fat",
        "Yao Lan",
        "Kong Jiehong",
        "Chang On Kay",
        "Tong Wing Fat",
        "Bruce Clark",
        "Chiang Chi Yuen",
        "Kong Ching Wan",
        "Ray Medina",
        "Wu Chi Ming"
    ]
}
```

无数据时返回
```json
{
    "names": null
}
```

**Comment by BurstWhite** [comment]
@Sh1n3zZ 你好，发送请求时返回404，服务器是否为开启状态？

**Comment by Sh1n3zZ** [comment]
如上个 commit
```Python
import http.client

conn = http.client.HTTPSConnection("localhost", 1145)
payload = ''
headers = {
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)'
}
conn.request("GET", "/needsub?homeworkid=1", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))
```
返回 sample
```json
{
    "Need2BSub": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7"
    ]
}
```

**Comment by BurstWhite** [comment]
收到
另: 请在/students返回学生姓名时同时返回学号,否则无法提交

**Comment by Sh1n3zZ** [comment]
@3q1u ,

已实现，
```Python
import http.client

conn = http.client.HTTPSConnection("localhost", 1145)
payload = ''
headers = {
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)'
}
conn.request("GET", "/students?class=12", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))
```

返回 Sample
```json
{
    "students": [
        {
            "name": "Ueno Ayato",
            "school_id": 37013120193
        },
        {
            "name": "Wu Ka Keung",
            "school_id": 37013120197
        },
        {
            "name": "Ethel Campbell",
            "school_id": 37013120051
        },
        {
            "name": "Tony Aguilar",
            "school_id": 37013120841
        },
        {
            "name": "George Fox",
            "school_id": 37013120695
        },
        {
            "name": "Mui Sze Yu",
            "school_id": 37013120611
        },
        {
            "name": "Cui Ziyi",
            "school_id": 37013120209
        },
        {
            "name": "Fan Jiehong",
            "school_id": 37013120380
        },
        {
            "name": "Yan Shihan",
            "school_id": 37013120809
        },
        {
            "name": "Nakamura Hina",
            "school_id": 37013120790
        },
        {
            "name": "Han Anqi",
            "school_id": 37013121000
        },
        {
            "name": "Kono Ayano",
            "school_id": 37013120770
        },
        {
            "name": "Lois Cook",
            "school_id": 37013120893
        },
        {
            "name": "Meng Ziyi",
            "school_id": 37013120879
        },
        {
            "name": "Mui Ka Man",
            "school_id": 37013120645
        },
        {
            "name": "Shi Yunxi",
            "school_id": 37013120524
        },
        {
            "name": "Morita Aoi",
            "school_id": 37013120020
        },
        {
            "name": "Nakagawa Ayato",
            "school_id": 37013120890
        },
        {
            "name": "Chow Chieh Lun",
            "school_id": 37013120673
        },
        {
            "name": "Kaneko Ayano",
            "school_id": 37013120294
        },
        {
            "name": "Jiang Zhiyuan",
            "school_id": 37013120995
        },
        {
            "name": "Jin Ziyi",
            "school_id": 37013120742
        },
        {
            "name": "Siu Yun Fat",
            "school_id": 37013120901
        },
        {
            "name": "Yamaguchi Ayato",
            "school_id": 37013120731
        },
        {
            "name": "Watanabe Tsubasa",
            "school_id": 37013120190
        },
        {
            "name": "Meng Sze Kwan",
            "school_id": 37013120132
        },
        {
            "name": "Andrew Martin",
            "school_id": 37013120290
        },
        {
            "name": "Duan Zhennan",
            "school_id": 37013120331
        },
        {
            "name": "Ota Rin",
            "school_id": 37013120311
        },
        {
            "name": "Sheh Wai San",
            "school_id": 37013120707
        },
        {
            "name": "Che Chiu Wai",
            "school_id": 37013120959
        },
        {
            "name": "Kudo Hikaru",
            "school_id": 37013120505
        },
        {
            "name": "Yue Wai Yee",
            "school_id": 37013120759
        },
        {
            "name": "Shen Zitao",
            "school_id": 37013120053
        },
        {
            "name": "Ichikawa Momoe",
            "school_id": 37013120297
        },
        {
            "name": "Maruyama Minato",
            "school_id": 37013120880
        },
        {
            "name": "Sit Fat",
            "school_id": 37013120612
        },
        {
            "name": "Yao Lan",
            "school_id": 37013120233
        },
        {
            "name": "Kong Jiehong",
            "school_id": 37013120218
        },
        {
            "name": "Chang On Kay",
            "school_id": 37013120954
        },
        {
            "name": "Tong Wing Fat",
            "school_id": 37013120421
        },
        {
            "name": "Bruce Clark",
            "school_id": 37013120886
        },
        {
            "name": "Chiang Chi Yuen",
            "school_id": 37013120500
        },
        {
            "name": "Kong Ching Wan",
            "school_id": 37013120164
        },
        {
            "name": "Ray Medina",
            "school_id": 37013120846
        },
        {
            "name": "Wu Chi Ming",
            "school_id": 37013120191
        }
    ]
}
```

**Comment by BurstWhite** [comment]
收到, 感谢

**Comment by BurstWhite** [comment]
似乎server没有更新? 查询class时仍然只返回名字

**Comment by Sh1n3zZ** [comment]
> 似乎server没有更新? 查询class时仍然只返回名字

收到，已更新
