### ISSUE TITLE
5.新的提交记录 POST

### ISSUE THREAD

**Issue by Sh1n3zZ** [aiaresearch/homeworkGun#13]

**Comment by Sh1n3zZ** [comment]
@3q1u 该接口是否为学生端该考虑的事情而非后端，实现时遇到问题，后端显然无法获取学生学号以及作业科目，或我这边与预留一个POST接口您OCR后直接对着这个接口POST

**Comment by BurstWhite** [comment]
> @3q1u 该接口是否为学生端该考虑的事情而非后端，实现时遇到问题，后端显然无法获取学生学号以及作业科目，或我这边与预留一个POST接口您OCR后直接对着这个接口POST

@Sh1n3zZ 可以，麻烦了

**Comment by Sh1n3zZ** [comment]
已添加，具体文档转至 #12
